apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: maps-service
  name: maps-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maps-service
  template:
    metadata:
      labels:
        app: maps-service
    spec:
      containers:
      - name: maps-service
        image: 261597695995.dkr.ecr.us-west-2.amazonaws.com/maps-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: maps-service
    k8s-app: maps-service
  name: maps-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: maps-service